// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// app_orth_rcpp
Rcpp::List app_orth_rcpp(Rcpp::NumericVector y, Rcpp::NumericMatrix MCX, double sig_hat, double k, int q2);
RcppExport SEXP _hdjmtTest_app_orth_rcpp(SEXP ySEXP, SEXP MCXSEXP, SEXP sig_hatSEXP, SEXP kSEXP, SEXP q2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type MCX(MCXSEXP);
    Rcpp::traits::input_parameter< double >::type sig_hat(sig_hatSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type q2(q2SEXP);
    rcpp_result_gen = Rcpp::wrap(app_orth_rcpp(y, MCX, sig_hat, k, q2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdjmtTest_app_orth_rcpp", (DL_FUNC) &_hdjmtTest_app_orth_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdjmtTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
