# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fast Approximate Orthogonalization :: Using C++
#' @keywords internal
#'
#' @noRd
NULL

app_orth_rcpp <- function(y, MCX, sig_hat, k, q2) {
    .Call(`_hdjmtTest_app_orth_rcpp`, y, MCX, sig_hat, k, q2)
}

